export const ADD_QUERY = 'ADD_QUERY'
export const DELETE_QUERY = 'DELETE_QUERY'
export const EDIT_QUERY = 'EDIT_QUERY'
export const FINISH_MEAL = 'FINISH_MEAL'
export const FETCH_RESULT = 'FETCH_RESULT'
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER"